# Generated by Django 5.0.7 on 2024-09-16 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contacts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="email"
                    ),
                ),
                ("country", models.TextField(verbose_name="Страна")),
                ("city", models.TextField(verbose_name="Город")),
                (
                    "street",
                    models.TextField(blank=True, null=True, verbose_name="Улица"),
                ),
                (
                    "house_number",
                    models.TextField(blank=True, null=True, verbose_name="Номер дома"),
                ),
            ],
            options={
                "verbose_name": "Контакты",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Введите название продукта",
                        max_length=255,
                        verbose_name="Название",
                    ),
                ),
                (
                    "model",
                    models.TextField(
                        blank=True,
                        help_text="Введите название модели",
                        null=True,
                        verbose_name="Модель",
                    ),
                ),
                (
                    "release_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="дата выхода"
                    ),
                ),
            ],
            options={
                "verbose_name": "Продукт",
                "verbose_name_plural": "Продукты",
            },
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("Завод", "Завод"),
                            ("Cеть", "Розничная сеть"),
                            ("Предприниматель", "Индивидуальный предприниматель"),
                        ],
                        help_text="Выберите тип поставщика",
                        verbose_name="тип поставщика",
                    ),
                ),
                (
                    "supplier_level",
                    models.IntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name="уровень в цепочке поставок",
                    ),
                ),
                (
                    "debt",
                    models.FloatField(
                        blank=True, null=True, verbose_name="Задолженность"
                    ),
                ),
                (
                    "release_date",
                    models.DateTimeField(
                        auto_now=True, null=True, verbose_name="дата создания"
                    ),
                ),
                (
                    "contacts",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="network_objects.contacts",
                        verbose_name="Контакты",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        to="network_objects.product",
                        verbose_name="Продукт",
                    ),
                ),
                (
                    "purveyor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="network_objects.supplier",
                        verbose_name="Поставщик",
                    ),
                ),
            ],
            options={
                "verbose_name": "Поставщик",
                "verbose_name_plural": "Поставщики",
            },
        ),
    ]
