# Generated by Django 5.0.7 on 2024-09-16 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network_objects", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="products",
            field=models.ManyToManyField(
                to="network_objects.product", verbose_name="Продукт"
            ),
        ),
    ]
