# Generated by Django 5.1.1 on 2024-09-16 20:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_objects', '0002_supplier_supplier_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('country', models.TextField(verbose_name='Страна')),
                ('city', models.TextField(verbose_name='Город')),
                ('street', models.TextField(blank=True, null=True, verbose_name='Улица')),
                ('house_number', models.TextField(blank=True, null=True, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='city',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='country',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='house_number',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='street',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='name',
            field=models.CharField(choices=[('Завод', 'Завод'), ('Сеть', 'Розничная сеть'), ('Предприниматель', 'Индивидуальный предприниматель')], help_text='Выберите тип поставщика', verbose_name='тип поставщика'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contacts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='network_objects.contacts', verbose_name='Контакты'),
        ),
    ]
