# Generated by Django 5.0.7 on 2024-09-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("network_objects", "0002_alter_supplier_products"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supplier",
            name="name",
            field=models.CharField(
                choices=[
                    ("Завод", "Завод"),
                    ("Сеть", "Розничная сеть"),
                    ("Предприниматель", "Индивидуальный предприниматель"),
                ],
                help_text="Выберите тип поставщика",
                verbose_name="тип поставщика",
            ),
        ),
    ]
